BEGIN TRANSACTION
ALTER TABLE [EL_PUNTERO].[TL_AERONAVE]
ADD PRIMARY KEY ([ID_Aeronave]);

ALTER TABLE [EL_PUNTERO].[TL_BAJA_SERVICIO_AERONAVE]
ADD PRIMARY KEY([ID_Baja_Servicio]);

ALTER TABLE [EL_PUNTERO].[TL_SERVICIO]
ADD PRIMARY KEY ([ID_Servicio]);

ALTER TABLE [EL_PUNTERO].[TL_RUTA]
ADD PRIMARY KEY ([ID_Ruta]);

ALTER TABLE [EL_PUNTERO].[TL_SERVICIO_RUTA]
ADD PRIMARY KEY ([ID_Servicio_Ruta]);

ALTER TABLE [EL_PUNTERO].[TL_CIUDAD]
ADD PRIMARY KEY ([ID_Ciudad]);

ALTER TABLE [EL_PUNTERO].[TL_TIPO_BUTACA]
ADD PRIMARY KEY ([ID_Tipo_Butaca]);

ALTER TABLE [EL_PUNTERO].[TL_BUTACA]
ADD PRIMARY KEY ([ID_Butaca]);

ALTER TABLE [EL_PUNTERO].[TL_PASAJE]
ADD PRIMARY KEY ([ID_Pasaje]);

ALTER TABLE [EL_PUNTERO].[TL_VIAJE]
ADD PRIMARY KEY ([ID_Viaje]);

ALTER TABLE [EL_PUNTERO].[TL_ITEM_DEVUELTO]
ADD PRIMARY KEY ([ID_Item_Devuelto]);

ALTER TABLE [EL_PUNTERO].[TL_DEVOLUCION]
ADD PRIMARY KEY ([ID_Devolucion]);

ALTER TABLE [EL_PUNTERO].[TL_REGISTRO_MILLAS]
ADD PRIMARY KEY ([ID_Registro]);

ALTER TABLE [EL_PUNTERO].[TL_ENCOMIENDA]
ADD PRIMARY KEY ([ID_Encomienda]);

ALTER TABLE [EL_PUNTERO].[TL_CLIENTE]
ADD PRIMARY KEY ([ID_Cliente]);

ALTER TABLE [EL_PUNTERO].[TL_CANJE]
ADD PRIMARY KEY ([ID_Canje]);

ALTER TABLE [EL_PUNTERO].[TL_COMPRA]
ADD PRIMARY KEY ([ID_Compra]);

ALTER TABLE [EL_PUNTERO].[TL_TIPO_DOCUMENTO]
ADD PRIMARY KEY ([ID_Tipo_Documento]);

ALTER TABLE [EL_PUNTERO].[TL_PRODUCTO]
ADD PRIMARY KEY ([ID_Producto]);

ALTER TABLE [EL_PUNTERO].[TL_TARJETA]
ADD PRIMARY KEY ([ID_Tarjeta]);

ALTER TABLE [EL_PUNTERO].[TL_TIPO_TARJETA]
ADD PRIMARY KEY ([ID_Tipo_Tarjeta]);

ALTER TABLE [EL_PUNTERO].[TL_USUARIO]
ADD PRIMARY KEY ([ID_Usuario]);

ALTER TABLE [EL_PUNTERO].[TL_ROL_USUARIO]
ADD PRIMARY KEY ([ID_Rol_Usuario]);

ALTER TABLE [EL_PUNTERO].[TL_ROL]
ADD PRIMARY KEY ([ID_Rol]);

ALTER TABLE [EL_PUNTERO].[TL_FUNCIONALIDAD_ROL]
ADD PRIMARY KEY ([ID_Funcionalidad_Rol]);

ALTER TABLE [EL_PUNTERO].[TL_FUNCIONALIDAD]
ADD PRIMARY KEY ([ID_Funcionalidad]);

COMMIT