BEGIN TRANSACTION

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [EL_PUNTERO].[Tr_DeshabilitarUsuariosConRolDeshabilitado]
ON [EL_PUNTERO].[TL_ROL]
AFTER UPDATE
AS BEGIN
	DELETE FROM [EL_PUNTERO].[TL_ROL_USUARIO]
	WHERE ID_Rol in (SELECT ID_Rol FROM [EL_PUNTERO].[TL_ROL] WHERE Habilitado=0) 
END
GO

COMMIT