BEGIN TRANSACTION

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [EL_PUNTERO].[Tr_DeshabilitarUsuariosConRolDeshabilitado]
ON [EL_PUNTERO].TL_ROL
AFTER UPDATE
AS BEGIN
	UPDATE [EL_PUNTERO].TL_USUARIO SET Habilitado = 0
	WHERE ID_Rol in (SELECT ID_Rol FROM [EL_PUNTERO].TL_ROL WHERE Habilitado=0) /*FROM INSERTED PUEDE SER TAMBIÉN??*/
END

COMMIT